pipeline {
    agent any
    
    environment {
        GITHUB_REPO_URL = 'https://github.com/Telana99/4038_kuruwitaarachchi-.git'
        
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: "${env.GITHUB_REPO_URL}"
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t app-server .'
            }
        }
        
        stage('Run Docker Image') {
            steps {
               sh 'docker run -d -p 3000:3000 app-server'
            }
        }
        
    }
}